---
- name: Check updates (production base)
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false

    - name: Get upgradable packages list
      ansible.builtin.command: apt list --upgradable
      register: apt_updates
      changed_when: false
      failed_when: false

    - name: Count updates
      ansible.builtin.set_fact:
        updates_count: "{{ apt_updates.stdout_lines | length - 1 }}"

    - name: Show result
      ansible.builtin.debug:
        msg: "Updates available: {{ updates_count }}"
