---
- name: Check updates
  hosts: all
  become: true

  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 3600
      changed_when: false

    - name: Count upgradable packages
      ansible.builtin.shell: |
        apt list --upgradable 2>/dev/null | grep -v "Listing..." | wc -l
      register: updates_count
      changed_when: false

    - name: Show result
      ansible.builtin.debug:
        msg: "Updates available: {{ updates_count.stdout }}"
